spring:
  application:
    name: library-management
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
          ddl-auto: create
          show-sql: true

